name: sign-all
on:
  workflow_dispatch:

jobs:
  build_sign_and_push:
    # Prevent running this on forks
    if: github.repository_owner == 'pdellaert'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Run npm install
        run: |
          npm ci
      - name: Build packages
        run: |
          npm run build
      - name: Execute signer to sign the plugins
        env:
          GCLOUD_CLIENT_EMAIL: ${{ secrets.GCLOUD_CLIENT_EMAIL }}
          GCLOUD_KEY: ${{ secrets.GCLOUD_KEY }}
          GCLOUD_KEYRING: ${{ secrets.GCLOUD_KEYRING }}
          GCLOUD_KEY_VERSION: ${{ secrets.GCLOUD_KEY_VERSION }}
          GCLOUD_LOCATION: ${{ secrets.GCLOUD_LOCATION }}
          GCLOUD_PRIVATE_KEY: ${{ secrets.GCLOUD_PRIVATE_KEY }}
          GCLOUD_PROJECT: ${{ secrets.GCLOUD_PROJECT }}
          PLUGIN_PUBLIC_KEY: ${{ secrets.PLUGIN_PUBLIC_KEY }}
          NODE_ENV: production
        run: node packages/signer/dist/index.js
      - name: Copy plugins to folder
        run: |
          mkdir -p plugins
          cp packages/signer/dist/plugins/*.json plugins/
      - name: Commit and push new plugins
        uses: EndBug/add-and-commit@v9
        with:
          add: plugins
          message: Adding all plugins after re-signing all
          committer_name: Github Actions
          committer_email: actions@github.com
